dSections = {
    '.aspack': 'Aspack packer',
    '.adata': 'Aspack packer/Armadillo packer',
    'ASPack': 'Aspack packer',
    '.ASPack': 'ASPAck Protector',
    '.boom': 'The Boomerang List Builder (config+exe xored with a single byte key 0x77)',
    '.ccg': 'CCG Packer (Chinese Packer)',
    '.charmve': 'Added by the PIN tool',
    'BitArts': 'Crunch 2.0 Packer',
    'DAStub': 'DAStub Dragon Armor protector',
    '!EPack': 'Epack packer',
    'FSG!': 'FSG packer (not a section name, but a good identifier)',
    '.gentee': 'Gentee installer',
    'kkrunchy': 'kkrunchy Packer',
    '.mackt': 'ImpRec-created section',
    '.MaskPE': 'MaskPE Packer',
    'MEW': 'MEW packer',
    '.MPRESS1': 'Mpress Packer',
    '.MPRESS2': 'Mpress Packer',
    '.neolite': 'Neolite Packer',
    '.neolit': 'Neolite Packer',
    '.nsp1': 'NsPack packer',
    '.nsp0': 'NsPack packer',
    '.nsp2': 'NsPack packer',
    'nsp1': 'NsPack packer',
    'nsp0': 'NsPack packer',
    'nsp2': 'NsPack packer',
    '.packed': 'RLPack Packer (first section)',
    'pebundle': 'PEBundle Packer',
    'PEBundle': 'PEBundle Packer',
    'PEC2TO': 'PECompact packer',
    'PECompact2': 'PECompact packer (not a section name, but a good identifier)',
    'PEC2': 'PECompact packer',
    'pec1': 'PECompact packer',
    'pec2': 'PECompact packer',
    'PEC2MO': 'PECompact packer',
    'PELOCKnt': 'PELock Protector',
    '.perplex': 'Perplex PE-Protector',
    'PESHiELD': 'PEShield Packer',
    '.petite': 'Petite Packer',
    '.pinclie': 'Added by the PIN tool',
    'ProCrypt': 'ProCrypt Packer',
    '.RLPack': 'RLPack Packer (second section)',
    '.rmnet': 'Ramnit virus marker',
    'RCryptor': 'RPCrypt Packer',
    '.RPCrypt': 'RPCrypt Packer',
    '.seau': 'SeauSFX Packer',
    '.sforce3': 'StarForce Protection',
    '.spack': 'Simple Pack (by bagie)',
    '.svkp': 'SVKP packer',
    'Themida': 'Themida Packer',
    '.Themida': 'Themida Packer',
    '.taz': 'Some version os PESpin',
    '.tsuarch': 'TSULoader',
    '.tsustub': 'TSULoader',
    'PEPACK!!': 'Pepack',
    '.Upack': 'Upack packer',
    '.ByDwing': 'Upack Packer',
    'UPX0': 'UPX packer',
    'UPX1': 'UPX packer',
    'UPX2': 'UPX packer',
    'UPX!': 'UPX packer',
    '.UPX0': 'UPX Packer',
    '.UPX1': 'UPX Packer',
    '.UPX2': 'UPX Packer',
    '.vmp0': 'VMProtect packer',
    '.vmp1': 'VMProtect packer',
    '.vmp2': 'VMProtect packer',
    'VProtect': 'Vprotect Packer',
    '.winapi': 'Added by API Override tool',
    'WinLicen': 'WinLicense (Themida) Protector',
    '_winzip_': 'WinZip Self-Extractor',
    '.WWPACK': 'WWPACK Packer',
    '.yP': 'Y0da Protector',
    '.y0da': 'Y0da Protector',

    '.00cfg': 'Control Flow Guard (CFG) section (added by newer versions of Visual Studio)',
    '.arch': 'Alpha-architecture section',
    '.autoload_text': 'cygwin/gcc',
    '.bindat': 'Binary data (also used by one of the downware installers based on LUA)',
    '.bootdat': 'section that can be found inside Visual Studio files; contains palette entries',
    '.bss': 'Uninitialized Data Section',
    '.BSS': 'Uninitialized Data Section',
    '.buildid': 'gcc/cygwin; Contains debug information (if overlaps with debug directory)',
    '.CLR_UEF': '.CLR Unhandled Exception Handler section',
    '.code': 'Code Section',
    '.cormeta': '.CLR Metadata Section',
    '.complua': 'Binary data, most likely compiled LUA',
    '.CRT': 'Initialized Data Section  (C RunTime)',
    '.cygwin_dll_common': "cygwin section containing flags representing Cygwin's capabilities",
    '.data': 'Data Section',
    '.DATA': 'Data Section',
    '.data1': 'Data Section',
    '.data2': 'Data Section',
    '.data3': 'Data Section',
    '.debug': 'Debug info Section',
    '.debug$F': 'Debug info Section (Visual C++ version <7.0)',
    '.debug$P': 'Debug info Section (Visual C++ debug information',
    '.debug$S': 'Debug info Section (Visual C++ debug information',
    '.debug$T': 'Debug info Section (Visual C++ debug information',
    '.drectve ': 'directive section (temporary; should not appear in a final PE image)',
    '.didat': 'Delay Import Section',
    '.didata': 'Delay Import Section',
    '.edata': 'Export Data Section',
    '.eh_fram': 'gcc/cygwin; Exception Handler Frame section',
    '.export': 'Alternative Export Data Section',
    '.fasm': 'FASM flat Section',
    '.flat': 'FASM flat Section',
    '.gfids': 'section added by new Visual Studio (14.0); purpose unknown',
    '.giats': 'section added by new Visual Studio (14.0); purpose unknown',
    '.gljmp': 'section added by new Visual Studio (14.0); purpose unknown',
    '.glue_7t': 'ARMv7 core glue functions (thumb mode)',
    '.glue_7': 'ARMv7 core glue functions (32-bit ARM mode)',
    '.idata': 'Initialized Data Section  (Borland)',
    '.idlsym': 'IDL Attributes (registered SEH)',
    '.impdata': 'Alternative Import data section',
    '.itext': 'Code Section  (Borland)',
    '.ndata': 'Nullsoft Installer section',
    '.orpc': 'Code section inside rpcrt4.dll',
    '.pdata': 'Exception Handling Functions Section (PDATA records)',
    '.rdata': 'Read-only initialized Data Section  (MS and Borland)',
    '.reloc': 'Relocations Section',
    '.rodata': 'Read-only Data Section',
    '.rsrc': 'Resource section',
    '.sbss': 'GP-relative Uninitialized Data Section',
    '.script': 'Section containing script',
    '.shared': 'Shared section',
    '.sdata': 'GP-relative Initialized Data Section',
    '.srdata': 'GP-relative Read-only Data Section',
    '.stab': 'Created by Haskell compiler (GHC)',
    '.stabstr': 'Created by Haskell compiler (GHC)',
    '.sxdata': 'Registered Exception Handlers Section',
    '.text': 'Code Section',
    '.text0': 'Alternative Code Section',
    '.text1': 'Alternative Code Section',
    '.text2': 'Alternative Code Section',
    '.text3': 'Alternative Code Section',
    '.textbss': 'Section used by incremental linking',
    '.tls': 'Thread Local Storage Section',
    '.tls$': 'Thread Local Storage Section',
    '.udata': 'Uninitialized Data Section',
    '.vsdata': 'GP-relative Initialized Data',
    '.xdata': 'Exception Information Section',
    '.wixburn': 'Wix section',
    'BSS': 'Uninitialized Data Section  (Borland)',
    'CODE': 'Code Section (Borland)',
    'DATA': 'Data Section (Borland)',
    'DGROUP': 'Legacy data group section',
    'edata': 'Export Data Section',
    'idata': 'Initialized Data Section  (C RunTime)',
    'INIT': 'INIT section (drivers)',
    'minATL': 'Section that can be found inside some ARM PE files; purpose unknown',
    'PAGE': 'PAGE section (drivers)',
    'rdata': 'Read-only Data Section',
    'sdata': 'Initialized Data Section',
    'shared': 'Shared section',
    'Shared': 'Shared section',
    'testdata': 'section containing test data (can be found inside Visual Studio files)',
    'text': 'Alternative Code Section'
}

machineDB = {
        0: "Unknown",
    0x0001: "Host",
    0x014c: "Intel 386",
    0x0162: "MIPS little-endian, 0x160 big-endian",
    0x0166: "MIPS little-endian",
    0x0168: "MIPS little-endian",
    0x0169: "MIPS little-endian WCE v2",
    0x0184: "Alpha_AXP",
    0x01a2: "SH3 little-endian",
    0x01a3: "SH3DSP",
    0x01a4: "SH3E little-endian",
    0x01a6: "SH4 little-endian",
    0x01a8: "SH5",
    0x01c0: "ARM Little-Endian",
    0x01c2: "ARM Thumb/Thumb-2 Little-Endian",
    0x01c4: "ARM Thumb-2 Little-Endian",
    0x01d3: "TAM33BD",
    0x01F0: "IBM PowerPC Little-Endian",
    0x01f1: "POWERPCFP",
    0x0200: "Intel 64",
    0x0266: "MIPS",
    0x0284: "ALPHA64",
    0x0366: "MIPS",
    0x0466: "MIPS",
    0x0520: "Infineon",
    0x0CEF: "CEF",
    0x0EBC: "EFI Byte Code",
    0x8664: "AMD64 (K8)",
    0x9041: "M32R little-endian",
    0xAA64: "ARM64 Little-Endian",
    0xC0EE: "CEE"
}

subsystemDB = {
    0: "IMAGE_SUBSYSTEM_UNKNOWN",
    1: "IMAGE_SUBSYSTEM_NATIVE",
    2: "IMAGE_SUBSYSTEM_WINDOWS_GUI",
    3: "IMAGE_SUBSYSTEM_WINDOWS_CUI",
    5: "IMAGE_SUBSYSTEM_OS2_CUI",
    7: "IMAGE_SUBSYSTEM_POSIX_CUI",
    8: "IMAGE_SUBSYSTEM_NATIVE_WINDOWS",
    9: "IMAGE_SUBSYSTEM_WINDOWS_CE_GUI",
    10: "IMAGE_SUBSYSTEM_EFI_APPLICATION",
    11: "IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER",
    12: "IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER",
    13: "IMAGE_SUBSYSTEM_EFI_ROM",
    14: "IMAGE_SUBSYSTEM_XBOX",
    16: "IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION"
}
